version: '3.9'

services:
  flaskapp:
    build:
      context: .
    container_name: flask-calendar
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - credentials:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - FLASK_ENV=production

volumes:
  credentials:
